### ISSUE TITLE
Add support for Dyn DNS

### ISSUE THREAD

**Issue by apple4ever** [felixfontein/acme-certificate#18]
I have a the playbooks to make this work with Dyn, but before I submitted a PR, I had a question.

They currently use the `uri` module to do the work. However, there is a [new module proposed for Dyn](https://github.com/ansible/ansible/pull/33222).

Should I wait til that's available or should I just submit what I got and rewrite it when necessary?

**Comment by felixfontein** [comment]
The new module won't make it into Ansible before 2.7, which is (judging from regular release schedules) at least 6 months in the future (maybe only 3, if the short time between 2.5 and 2.6 will become the new standard). So I guess using the `uri` module for now is totally fine, and then updating it once the `dyn_record` module is merged.

**Comment by felixfontein** [comment]
Dyn has been bought by Oracle and will be terminated in 2020. Doesn't sound like something that needs support...

**Comment by apple4ever** [comment]
Forgot I opened this! Yes I saw that, and I stopped work on the Dyn module for the same reason. Definitely not needed to support.
