### ISSUE TITLE
Publish to Galaxy?

### ISSUE THREAD

**Issue by colans** [felixfontein/acme-certificate#19]
I can't seem to find this project on https://galaxy.ansible.com/ .  If you've published it there, please provide the URL in the README here.  Otherwise, please publish it (and also add the URL to the README).  Thanks!

**Comment by felixfontein** [comment]
It's not available on Galaxy yet. I will look into it probably this weekend.

**Comment by felixfontein** [comment]
It's now available [here](https://galaxy.ansible.com/felixfontein/acme_certificate).
