### ISSUE TITLE
Namespace variables

### ISSUE THREAD

**Issue by nwmcsween** [felixfontein/acme-certificate#24]
I have previous yaml of server_name and domains, could acme-certificate namespace the vars it uses?

**Comment by felixfontein** [comment]
If you pass `server_name` and `domains` (with the values needed by this role) as role parameters, your global variables of these names shouldn't be touched. (If you didn't define them as extra vars - see https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)
